#!/usr/bin/env ruby
require 'rbtree'

# Our test cases will always use the same dictionary file (with SHA1
# 6b898d7c48630be05b72b3ae07c5be6617f90d8e). Running `test/harness`
# will automatically download this dictionary for you if you don't
# have it already.

path = ARGV.length > 0 ? ARGV[0] : '/usr/share/dict/words'
tree = RBTree.new
File.read(path).split.each do |word|
  tree[word] = word
end

#puts entries.include?("Asteroidea")
#puts entries.include?("asteroidea")

contents = $stdin.read
contents.each_line do |line|
  splitted = line.split
  splitted.each_with_index do |word, index|
    if !tree[word.downcase]
      splitted[index] = "<#{word}>"
    end
  end
  puts splitted.join(" ")
end
